services:
  mariadb:
    volumes:
      - mariadb:/var/lib/mysql
    container_name: mybb_db
    image: mariadb:10.6.16
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: mybb
    ports:
      - 3312:3306
    networks:
      net:

  mybb:
    volumes:
      - ./app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    container_name: mybb
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - "mariadb"
    networks:
      net:

  webserver:
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/mybb.conf:/etc/nginx/conf.d/default.conf
    container_name: mybb_ws
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8585:80"
    depends_on:
      - "mybb"
    networks:
      net:

networks:
  net:
    name: mybb-network
    external: false

volumes:
  mariadb:
    name: mybb-dbdata
